version: '3.8'

services:
  backend:
    build: .
    container_name: lucy-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - lucy-network
    environment:
      - LUCY_MODE=real
    volumes:
      - ./backend:/backend
      - ./frontend:/frontend

  mongo:
    image: mongo:4.4
    container_name: lucy-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/root/fastapi-data/lucy/db
      - /root/fastapi-data/kdydata:/data/import
      - /root/fastapi-data/lucy/log:/root/fastapi-data/lucy/log
      - /root/fastapi-data/lucy/data:/root/fastapi-data/lucy/data
      - /root/fastapi-data/lucy/files:/root/fastapi-data/lucy/files
    networks:
      - lucy-network
    command: >
      bash -c "
      mongod --bind_ip_all &
      sleep 5 &&
      mongoimport --host localhost --db stockdb --collection Config --file /data/import/stockdb.Config.json --jsonArray &&
      mongoimport --host localhost --db stockdb --collection SchedulerJob --file /data/import/stockdb.SchedulerJob.json --jsonArray &&
      mongoimport --host localhost --db stockdb --collection Users --file /data/import/stockdb.Users.json --jsonArray &&
      tail -f /dev/null
      "
volumes:
  mongo_data:

networks:
  lucy-network:
