version: '3.8'

services:
  backend:
    build: .
    container_name: ipo-scheduler
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - ipo-network
    environment:
      - IPO_SCHEDULER_MODE=real
    volumes:
      - ./backend:/backend
      - ./frontend:/frontend
      - /home/kdy987/fastapi/ipo-scheduler/log:/log
      - /etc/localtime:/etc/localtime:ro  # 호스트 시간대 설정 마운트      
    restart: always  # 서버 재시작 시 항상 컨테이너를 재시작

  mongo:
    image: mongo:4.4
    container_name: ipo-mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/kdy987/fastapi/mongodb:/data/db
      - /home/kdy987/fastapi/kdydata:/data/import
      - /home/kdy987/fastapi/mongodb_backup:/data/backup
      - /etc/localtime:/etc/localtime:ro  # 호스트 시간대 설정 마운트
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh  # 스크립트 파일 마운트                  
    networks:
      - ipo-network
    restart: always  # 서버 재시작 시 항상 컨테이너를 재시작

networks:
  ipo-network:
