version: '3.8'

services:
  backend:
    build: .
    container_name: ipo-scheduler
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - ipo-network
    environment:
      - IPO_SCHEDULER_MODE=real
    volumes:
      - ./backend:/backend
      - ./frontend:/frontend
      - /home/kdy987/fastapi/ipo-scheduler/log:/log
      - /etc/localtime:/etc/localtime:ro  # 호스트 시간대 설정 마운트      
    restart: always  # 서버 재시작 시 항상 컨테이너를 재시작

  mongo:
    image: mongo:4.4
    container_name: ipo-mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/kdy987/fastapi/mongodb:/data/db
      - /home/kdy987/fastapi/kdydata:/data/import
      - /etc/localtime:/etc/localtime:ro  # 호스트 시간대 설정 마운트            
    networks:
      - ipo-network
    command: >
      bash -c "
      # Lock 파일이 있으면 삭제
      if [ -f /data/db/mongod.lock ]; then
          rm /data/db/mongod.lock;
          echo 'Removed mongod.lock';
      fi

      # MongoDB 실행
      mongod --bind_ip_all & 

      # MongoDB가 준비될 때까지 대기
      until mongo --host localhost --eval 'print(\"MongoDB is ready\")'; do
          sleep 5;
      done;

      echo 'MongoDB 기동 완료. Import 시작...';

      # Import 명령어 수행 (중복 문서 오류 방지)
      mongoimport --host localhost --db ipo-scheduler --collection Config --file /data/import/Config.json --jsonArray --mode=upsert || echo 'Config import 실패';
      mongoimport --host localhost --db ipo-scheduler --collection SchedulerJob --file /data/import/SchedulerJob.json --jsonArray --mode=upsert || echo 'SchedulerJob import 실패';
      mongoimport --host localhost --db ipo-scheduler --collection Users --file /data/import/Users.json --jsonArray --mode=upsert || echo 'Users import 실패';
      mongoimport --host localhost --db ipo-scheduler --collection EventDays --file /data/import/EventDays.json --jsonArray --mode=upsert || echo 'EventDays import 실패';
      mongoimport --host localhost --db ipo-scheduler --collection Ipo --file /data/import/Ipo.json --jsonArray --mode=upsert || echo 'Ipo import 실패';
      mongoimport --host localhost --db ipo-scheduler --collection IpoHistory --file /data/import/IpoHistory.json --jsonArray --mode=upsert || echo 'IpoHistory import 실패';

      # MongoDB를 백그라운드에서 계속 실행
      tail -f /dev/null
      "
    restart: always  # 서버 재시작 시 항상 컨테이너를 재시작

networks:
  ipo-network:
