version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27000:27017
    volumes:
      - ./mongodata:/data/db
volumes:
  mongodata:
      driver: local

networks:
    default: 
        name: mongodb_network